### ISSUE TITLE
Customize the scroll bar

### ISSUE THREAD

**Issue by zugzwang03** [sharanya-mitra/Todolist#13]
Can I customize the scroll bar in accordance with your latest design on the website?
It would be a minor change, but it will look perfect with respect to the whole viewpoint.
Can I make this contribution under Hacktoberfest'22?

**Comment by zugzwang03** [comment]
Can I be assigned to it as well, so that I can start my work?
 @Rick-mad-lab

**Comment by Rick-mad-lab** [comment]
assigned
!
